name: Build For macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
      - name: Setup GCC
        run: apt-get -y install mingw-w64
      - name: Make Samples
        run: cd malware; make CC=x86_64-w64-mingw32-gcc
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Check Go version
        run: go version
      - name: Build
        run: GOOS=darwin GOARC=AMD64 go build
      - name: Pack release
        run: tar cfvz itachi_darwin_amd64.tgz itachi #LICENSE README.md cia_example.yaml filter_example.yaml
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: itachi_darwin_amd64.tgz
